### ISSUE TITLE
Inclusion of Beta Decay Data

### ISSUE THREAD

**Issue by kgleach** [ElectroweakGroup/Database_Extraction_Tool#10]
I wanted to create this thread @wmcdonal so we could discuss this openly.  We need to read in a new set of data as our next step. The first two things needed (that we will expand on later) are below:

- [x] Find out where the data is that NuDat uses, and look at the file (if it is different from the ENSDF).  I have contacted Alejandro Sonzogni at BNL to get some information on this.

- [x] Read in the same information that NuDat does, and assign each value so we can perform mathematical operations on them.

**Comment by matmarti** [comment]
@kgleach Just want to confirm that this thread is for pulling beta decay information. We want information such as branching ratios and ft values correct? I am marking the first option as complete based on this assumption, as we found the data in the ENSDF file.

**Comment by kgleach** [comment]
@matmarti yes, that part can be check off.

**Comment by wmcdonal** [comment]
The program is now able to extract and plot B-decay information as of version 0.6.0. Now closing this issue.
