### ISSUE TITLE
Plotting Data

### ISSUE THREAD

**Issue by kgleach** [ElectroweakGroup/Database_Extraction_Tool#11]
I just tried to plot states in Eu up to 4 MeV, and got this (title is correct, plot is not).
![eu_1to299_4 _4000](https://user-images.githubusercontent.com/29310906/27809988-1b57aab4-6012-11e7-8171-664462fa5850.gif)

**Comment by wmcdonal** [comment]
@kgleach, I just checked all of the even-numbered isotopes from 140Eu to 160Eu using the online ensdf database, and all of the 4+ states listed in the database are shown in the plot that you posted. What are you seeing in the plot that is incorrect?

**Comment by kgleach** [comment]
@wmcdonal you are right, I'm amazed actually that there isn't more data known on the Eu isotopes...
