### ISSUE TITLE
Testing cases for Evaluated Nuclear Structure Data

### ISSUE THREAD

**Issue by kgleach** [ElectroweakGroup/Database_Extraction_Tool#2]
Trying:
Element - Gd (no isotope range)
Spin - 2+
Energy Bound - 2000 keV

Does not work, error:
Error with Y (27-) at loop 3a
Error with Z (28-) at loop 3a
Error with U (27+) at loop 2a
Error with V (29+) at loop 2a
Warning:No data filtered/selected for 151Gd.
Warning:No data filtered/selected for 153Gd.
Warning:No data filtered/selected for 155Gd.
Warning:No data filtered/selected for 157Gd.
Traceback (most recent call last):
  File "THIS_WORKS.py", line 58, in <module>
    function(option)
  File "THIS_WORKS.py", line 16, in function
    userInput = ided.datExp(option,True,True)
  File "/home/kleach/Work/Database_Extraction_Tool/isotopeDataExportingDat.py", line 78, in datExp
    indata=dc.data('ensdf.'+str(i).zfill(3),itervar,'EoL',energyLim)
  File "/home/kleach/Work/Database_Extraction_Tool/dataClass.py", line 196, in __init__
    addUncert(filtDataSet,line)
  File "/home/kleach/Work/Database_Extraction_Tool/functions.py", line 50, in addUncert
    digit = int(numberino[-1-i])+int(uncert[-1-i])
ValueError: invalid literal for int() with base 10: '.'

**Comment by kgleach** [comment]
Trying:
Element - O (no isotope range)
Spin - 0+
Energy Bound - 10000 keV

Error with 1410E 3- at loop 3b
Error with 2250E 3- at loop 3b
Error with 2300E 6+ at loop 2b
Error with 2550E 1- at loop 3b
Error with 2600E 1- at loop 3b
Error with 2735E (4+) at loop 2b
Error with 2980E 9- at loop 3b
Error with 2980E 8+ at loop 2b
Error with 1415E (9/2+) at loop 2b
Error with 1415E (9/2+) at loop 2b
Error with 1510E (9/2+) at loop 2b
Error with 1510E (9/2+) at loop 2b
Error with 1595E (9/2+) at loop 2b
Error with 1595E (9/2+) at loop 2b
Error with 1660E (11/2-) at loop 3b
Error with 1660E (11/2-) at loop 3b
Error with 1960E (13/2+) at loop 2b
Error with 1960E (13/2+) at loop 2b
Error with 2020E (13/2+) at loop 2b
Error with 2020E (13/2+) at loop 2b
Error with 2170E 5/2+ at loop 2b
Error with 2210E 7/2- at loop 3b
Warning:No data filtered/selected for 17O.
Warning:No data filtered/selected for 19O.
Traceback (most recent call last):
  File "THIS_WORKS.py", line 58, in <module>
    function(option)
  File "THIS_WORKS.py", line 16, in function
    userInput = ided.datExp(option,True,True)
  File "/home/kleach/Work/Database_Extraction_Tool/isotopeDataExportingDat.py", line 78, in datExp
    indata=dc.data('ensdf.'+str(i).zfill(3),itervar,'EoL',energyLim)
  File "/home/kleach/Work/Database_Extraction_Tool/dataClass.py", line 196, in __init__
    addUncert(filtDataSet,line)
  File "/home/kleach/Work/Database_Extraction_Tool/functions.py", line 50, in addUncert
    digit = int(numberino[-1-i])+int(uncert[-1-i])
ValueError: invalid literal for int() with base 10: 'E'

**Comment by kgleach** [comment]
There seems to be a fairly major issue with the data parsing mechanism.  I've been trying getting 2+ states up to 2 MeV across the isotopic chain for several heavier cases (including Sn, attached) and in nearly all cases it is skipping various nuclei/values.  It gives different errors, but they are usually something like this:
Error with 2.70E (0+) at loop 2b
Error with 3.88E (0+) at loop 2b
Error with 4.90E (0+) at loop 2b
Warning:No data filtered/selected for 109Sn.
Warning:No data filtered/selected for 111Sn.
Warning:No data filtered/selected for 113Sn.
Error with 1785.9215(9 (13/2-) at loop 3b
Warning:No data filtered/selected for 115Sn.
Warning:No data filtered/selected for 117Sn.
Error with 6.9E 3- at loop 3b
Error with 24.3E (3-) at loop 3b
Warning:No data filtered/selected for 118Sn.
Warning:No data filtered/selected for 119Sn.
Error with 13.3E 32+ at loop 2a
Error with 16.9E 0+ at loop 2b
Error with 19.2E (1-) at loop 3b
Error with 19.4E (1-) at loop 3b
Error with 20.6E (1-) at loop 3b
Error with 20.9E 153- at loop 3a
Error with 20.9E 153- at loop 3a
Error with 25.0E (3-) at loop 3b
Error with 27.9E 151- at loop 3a
Error with 27.9E 151- at loop 3a

Now included in that is  a statement that says "Warning:No data filtered/selected for 118Sn", which just isnt true...since there is a 2+ state at 1230 keV in 118Sn.
![1sn_299sn2 _every_1_fil](https://user-images.githubusercontent.com/29310906/26995824-2da472e0-4d2c-11e7-9038-82d1115c9379.gif)

**Comment by ElectroweakGroup** [comment]
Just looked into both of these things quickly. The first two issues should be solved when Will gets his code implemented as it accounts for both of these formatting types. The last issue is even simpler, the 2+ state for 118Sn is simply not in the data file. Below is the line from the ensdf file that I think should be this state, but it is not written as if it is a state at all.

118SN  G  1229.68  2 100       E2                                           A   

This is the only place that I saw 1229.68 appear in the 118SN section, so I believe it must be the state. Unfortunately, the ensdf documentation says that only the values where the G in that line is an L are states. Not really sure why it is written this way, but that is the reason for the issue.

**Comment by wmcdonal** [comment]
I have corrected the source of the ValueError that was crashing the program in the first two issues. Any statements that indicate an error produced at a specific loop are produced by the section of Marcus's code that reads spin states - which is one of the sections that I am rewriting.

Regarding the 118Sn 2+ issue, the ensdf file does indeed have this state listed on line 1861:
`118SN  L   1229.666162+                0.485 PS  19 `
This is an example of a state that Marcus's data searching algorithm is unable to correctly identify. If I use my code to search for all states (because I have not yet implemented the option to search for specific spin states) of 118Sn up to 2 Mev, the 2+ state in question is extracted and plotted:
![118sn_118sn_every_1_fil](https://user-images.githubusercontent.com/28356011/26998709-3aae3296-4d45-11e7-87ec-a9553ee7061d.png)

**Comment by kgleach** [comment]
Hi Will,  regarding the 1229 state.  Take a look at the PDF version of the ENSDF file, the first excited state quoted there is 1229.666(16).  Is that not in the text file you have?

**Comment by kgleach** [comment]
Just to add another case (because I was looking at it randomly).  It is extracting 4+ states in Cr correctly HOWEVER it has missed one at 1434.091(14).  These types of problems are EXTREMELY difficult to diagnose because at first glance it looks like it is working correctly.  I suspect the changes you are making will solve this, but I just wanted to make you aware of it.
![1cr_299cr4 _every_1_fil](https://user-images.githubusercontent.com/29310906/27045693-f7bd31d2-4f5e-11e7-9551-9aa82d2c3ae6.gif)

**Comment by wmcdonal** [comment]
Master has been updated with the new code that does not produce this problem and therefore I am closing the issue.
