### ISSUE TITLE
Energies labelled with letters (X,Y...)

### ISSUE THREAD

**Issue by matmarti** [ElectroweakGroup/Database_Extraction_Tool#4]
Some states are labelled with letters rather than energies. In the ENSDF manual it says that these represent occurrences but its hard to tell how to interpret them. A specific case is 88Tc ground state, where the state is labelled X rather than 0.0..

**Comment by kgleach** [comment]
@matmarti This is due to the fact that the difference in energy between the ground state and some excited state is known, however the nature of the gs is not (ie they may not know if that assignment is actually the gs).  Usually they will represent the excited state energy as X+ (some energy)

**Comment by matmarti** [comment]
That makes sense. For the purposes of this program, should we assume that the first state is the ground state and plot it as such? If so, how should we go about denoting that it is labelled as an X state by the ensdf file?

**Comment by kgleach** [comment]
@matmarti Let's discuss this in person.  I'm not sure yet how we should deal with that in the program.

**Comment by wmcdonal** [comment]
As we discussed in person, the program now identifies ground states with missing energy data and sets the energy of the ground state (before the mass data is incorporated) to zero and labels the spin of the ground state as 'X'. The image below shows the mass pabarbola for A = 88, where 88Tc shows this behavior.
![large_parabola_88_0k](https://user-images.githubusercontent.com/28356011/27743287-b280138c-5d78-11e7-892c-357b87c2f656.png)
Any excited states are suppressed as the user will have to read the ensdf comments anyway if they are interested in those states. The below image shows this case for both 88Tc and 90Tc.
![large_tc_85to90__9999999](https://user-images.githubusercontent.com/28356011/27743374-09b90e06-5d79-11e7-9ccc-c55940738b11.png)

**Comment by kgleach** [comment]
@wmcdonal I think that is all we can do for now.  You can go ahead and close this issue.
