### ISSUE TITLE
Pulling Errors

### ISSUE THREAD

**Issue by matmarti** [ElectroweakGroup/Database_Extraction_Tool#5]
I just went through U-235 and checked all states up to 200keV. Everything lines up except the error. The program is not keeping all digits of the error. For example, the second excited state of U-235 is 13.0339(21), and the program is pulling that out as 13.0339 +- 0.002, leaving off the 1.

Also for the first excited state, the ensdf file reads 0.076(4) and the program plots 0.076 +- 0.68. I don't know where this number came from. Looking into it

**Comment by kgleach** [comment]
Element: Pb
Spin: 2+
Energy Bound: 2000 keV

It doesn't plot, and gives an error:
Traceback (most recent call last):
  File "THIS_WORKS.py", line 64, in <module>
    function(option)
  File "THIS_WORKS.py", line 17, in function
    userInput = ided.datExp(option,True,True)
  File "/home/kleach/Work/Database_Extraction_Tool/newIsotopeDataExportingDat.py", line 83, in datExp
    indata.filterData(wantedSpins,UI) #FIXME bring back functionality
  File "/home/kleach/Work/Database_Extraction_Tool/newDataClass.py", line 241, in filterData
    if(spinMatchFinder(wantedString, self.data[i][1])):
  File "/home/kleach/Work/Database_Extraction_Tool/spinSearch.py", line 55, in spinMatchFinder
    [lhs,rhs] = tempList[0].split(':')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by matmarti** [comment]
From my first post, I found the mistake with the last digit of error not being kept, and that issue has been resolved. The 0.688 is baffling me because that number appears nowhere in the data file. I'll keep looking for where that error comes from
