### ISSUE TITLE
Plot Not Updating

### ISSUE THREAD

**Issue by kgleach** [ElectroweakGroup/Database_Extraction_Tool#6]
@matmarti When I try to plot the mass parabola, it seems to gather the data and attempt to plot it, however the image shown is still the nuclear chart...

**Comment by matmarti** [comment]
@kgleach That was an issue I found over the weekend. That has been fixed on the branch labelled Matt_Filenamebool_Fix and will be pushed to master at some point today

**Comment by matmarti** [comment]
Just pushed the branch with the fix to the master
