### ISSUE TITLE
Minor Change

### ISSUE THREAD

**Issue by kgleach** [ElectroweakGroup/Database_Extraction_Tool#7]
@matmarti For the Evaluated Beta Decay Information program, could you please do the following:

1) Remove the "Spin" option, and replace it with an upper energy bound.  Thereby showing all spins within a given window.
2) The parent and isotope boxes should be swapped, and the titles should be "A" and "Element"
3) The title should be simpler as well.  Try something like "beta- decay of ^AX at XX K"

**Comment by kgleach** [comment]
@matmarti For the Evaluated Nuclear Structure Extraction, you can remove the Temperature box, as well as the "Include Binding" checkbox

**Comment by kgleach** [comment]
@matmarti Since you are now taking the Temperature box away, you can also remove the "0+" superscript indicating the atomic charge state in the plots for this section.

**Comment by kgleach** [comment]
For the Evaluated Beta Decay Information program again, could you please set it so that if a Temperature is not entered it reads it as 0?  Right now the program crashes if it does not have a T:

Traceback (most recent call last):
  File "THIS_WORKS.py", line 63, in <module>
    function(option)
  File "THIS_WORKS.py", line 17, in function
    userInput = ided.datExp(option,True,True)
  File "/home/kleach/Work/Database_Extraction_Tool/newIsotopeDataExportingDat.py", line 36, in datExp
    from Beta_GUI import betaoutputs
  File "/home/kleach/Work/Database_Extraction_Tool/Beta_GUI.py", line 168, in <module>
    class betaoutputs:
  File "/home/kleach/Work/Database_Extraction_Tool/Beta_GUI.py", line 176, in betaoutputs
    temp=float(temp)
ValueError: could not convert string to float:

**Comment by matmarti** [comment]
Spin option has been removed and replaced with an upper energy bound. Temperature has been set so an empty value gets set to zero. A and Element have been swapped in location. None of the plotting things have been taken care of yet. I want to wait until we have everything else working fully before I go in and set specific plotting titles for each of those as they all use the same plotting script and it would be easier to do all at once.

**Comment by kgleach** [comment]
@matmarti I know we've discussed this before, but can we see about making the window and plots larger?  Also, we should increase resolution and quality of the plots.

**Comment by matmarti** [comment]
Temperature and binding options have been removed from the Evaluated Structure GUI. Remaining issues are:
    1) Titles of the plots
    2) State labels still include 0+ always
    3) Plots and windows have not been increased in size

**Comment by matmarti** [comment]
I have updated the plotting so that the titles now reflect what is being plotted. 

When the plots appear in the GUIs, they look a little odd, but this is because I was trying to make them higher quality (and succeeded). The images are now four times larger than they were originally with much greater resolution. The images you see are shrunken versions, which is why they appear a little odd. The GUI plots are also 1.2 times larger (about as large as my screen, keeping the aspect ratio).

If you click on the FULL SCREEN buttons, the actual image will pop up and you can see the increased resolution.

I removed the 0+ from the labels for the excited state button, but left it for the others as there is still an ionization option available.  If we want the program to read whether ionization happened and only plot the ionization states if it has, that is possible but non-trivial so I want feedback before I go do this.

Please update me on any comments or changes that you have

**Comment by kgleach** [comment]
@matmarti I will close this for now, as the issues you list above have been corrected for the time being.  We should open a new thread to discuss specific detail changes when they arise.

**Comment by kgleach** [comment]
@matmarti I reopened this because the image being shown in the program (not fullscreen) has a very poor quality.  I suspect this has to do with its ability to show such a high-resolution image in that small space.  Can this please be fixed.

**Comment by matmarti** [comment]
@kgleach The branch has been updated to reflect this. The plots being made are now of slightly higher quality than those being made before today, but the change to make them extremely high is very easy.

I tested the really high resolution ones with the poster on overleaf and after downloading and zooming way in they look really good.

**Comment by kgleach** [comment]
@matmarti is there a way to show the current resolution when it plots in the box, but when you click full screen it generates the "extremely high" resolution one?

**Comment by matmarti** [comment]
@kgleach I am working on that. Requires the code to create two different plots

**Comment by matmarti** [comment]
@kgleach This issue should be fixed with the last push to the Matt_GUI_Images branch
